# Generated by Django 3.0.5 on 2020-10-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='media/')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
