# Generated by Django 3.0.5 on 2020-10-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201004_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
